[project]
name = "botica-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.2.0",
    "fastapi[standard]>=0.141.1",
    "bcrypt<4.1",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.3.6",
    "python-jose[cryptography]>=3.5.0",
    "cloudinary>=1.46.2",
    "tzdata>=2026.4",
    "sqlmodel>=0.0.47",
    "alembic>=1.20.0",
    "pyjwt>=2.15.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "httpx>=0.28.1",
]
